### ISSUE TITLE
Slice by slice metrics

### ISSUE THREAD

**Issue by Aaronearlerichardson** [sct-pipeline/nadia#1]
The code you made works amazingly. However for the compute_metrics code I'm looking to compute mtr and dpi metrics for each of the 28 cross sectional slices of the image instead of an average for all 28. I edited your code a little to accomplish this and it works but it is very slow. If you look through the edited compute metrics script, you'll notice it's basically the same but I run the sct_extract_metric command through a for loop. Notice the SUBJECT variable is just your subject variable from the run_process script but exported to here. 

Is there some way to run the extract metric code so that it calculates all 28 metrics for an image and then saves them all once as opposed to what I am doing which is calculate one slice and then save once and repeating 28 times. I'm hoping this will make the code run faster. If you have any other suggestions for running faster that would help a lot as well.
[Julien's_Pipeline_edited.zip](https://github.com/sct-pipeline/nadia/files/2098479/Julien.s_Pipeline_edited.zip)

Thank you!

**Comment by jcohenadad** [comment]
Dear Aaron, thank you for your feedback. Unfortunately there is currently no other way than to loop in bash and iterate with -z input param to `sct_extract_metric`. The issue is known (see here: https://github.com/neuropoly/spinalcordtoolbox/issues/1213) and we hope to find the time to solve it soon. 

Please note also that if the goal is ultimately to average those slices together (or some of it), it will be more robust to estimate from a group of slices at the first place, because of the method used for metric quantification (map).

**Comment by jcohenadad** [comment]
@Aaronearlerichardson v3.2.2 now makes it possible to extract metric per each slice (or vertebral level). For more information please see: https://github.com/neuropoly/spinalcordtoolbox/pull/1875 and the usage: `sct_extract_metric -h`
